var delay=100
var fcontent=new Array()
begintag='<div style="font-family: monospace; white-space: pre;">'
fcontent[0]="                                                                    <br>                                                                    <br>                                                                    <br>                        :N               .                          <br>                       .M,O. MSUZBr   ,7jXB                         <br>                       N: BM20 Li M8JqY,. ji                        <br>                       B0r:         ;i JX M.                        <br>                     7U:               i.B7                         <br>                    qU:          iu.     ,M                         <br>                   B7YB5  :q.    kB8,.    :B                        <br>                  B7..  :LPGYU:    .:.     UF                       <br>                 U1      r  :r              B.                      <br>                 M.                         rE                      <br>                 O:                          B.                     <br>                 :M                          7q                     <br>                  07                          B                     <br>                  .B                          q7                    <br>                   B.                         :G                    <br>                   5v                          B.                   <br>                   7P                          JBj.                 <br>                   .B                            :USL .vj  .        <br>                    B.                              iNB:LZLuZ.      <br>                    0r                                iE    5u      <br>                    7P                                 :B   :Mr     <br>                    .B                                  FS   G7     <br>                     B.                                 .B   B      <br>                     Y5                              .,. Gr  B.     <br>                      B                            ..,.. jY BU      <br>                      j2                         ..,,... UBUY       <br>                       Br                    ..,,:.,... .O          <br>                     :uuB;        . . ....,.,.,......  .BX..,.:rBi  <br>                   YNY   8U  ......,................ .JP. :rr7i:BB  <br>             2X  i8v      iBB,    .............    :UXMU         :  <br>             YBBMJ        2Y:5FY;:.           .:ruSSi  ,kF,         <br>               ..       .B:    :7JF21uuYYYjUFU5J7,       ,11L:      <br>                        B.           ..,.,..                .iBB    <br>                    kBBB:                                     B7    <br>                     .NU                                            <br>                                                                    <br>                                                                    <br>" 
fcontent[1]="                                                                    <br>                                                                    <br>                      .J2     v                                     <br>                     YL,P2FP7B00:  iYLruS                           <br>                    jk,EFi2, : .S2GL... M                           <br>                   .ZF:          ., :Z.2:                           <br>                  vv                  LB                            <br>                 qLU7    .    iBu      UY                           <br>                M7:BF  .Mi    ,MG:,     Gi                          <br>               Zr    .7UB01r     .       B                          <br>              ;k          .              v5                         <br>              Ur                          M.                        <br>              iS                          L2                        <br>               M,                          M                        <br>               ,O                          U7                       <br>                0:                         :E                       <br>                LY                          M                       <br>                ,0                          25                      <br>                 O                           U1L:                   <br>                 E,                            :Lkr.:r              <br>                 jL                               iBP,0J17          <br>                 :k                                 j7   MU         <br>                  M                                  Xr   jU        <br>                  N:                                 .B.   M:       <br>                  LU                                . q7  .0        <br>                   M                              .,. rP   B,       <br>                   S7                           ..... ,q :O,        <br>                    M                        ..,..... i87Y   i      <br>                    .q                  . ..,.,.....  BL::77rBB.    <br>          YBBi .,::i,GB.   . . ........,..........  ,Z:      .2:    <br>           :P0Lrri:.  :qr    ............ . . .   ,5B               <br>                   .    Y8YL:      ... . .     .i1U;iLvr,.          <br>                  7BBUr7rLYXqL7i:..     ..,:rLUuL.    .:777Bq       <br>                   :Li       .:rvjjuJuYuJUL7i,             5B.      <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>" 
fcontent[2]="                                                                    <br>                   .                                                <br>                  0Xu  r7 i5      :F5                               <br>                 ur BPLB:Gk;Mv.:jL: 5,                              <br>                 Z1vq:..    :7SX .r X:                              <br>                Y1:              F7ju                               <br>              i5.                  1S                               <br>             JUrBu   ,.    0B2      U2                              <br>            YZ.iu.  JB. ,   L7i.     Mi                             <br>           :O ..  .SBBBM.    ...     .B                             <br>           E:        ii               2Y                            <br>           O.                          B                            <br>           LF                          UJ                           <br>            M.                         .M                           <br>            i0                          G:                          <br>             B                          rX                          <br>             ki                         .B                          <br>             LU                          8B.                        <br>             .8                           7U17.  ..                 <br>              M                              rU1E7E5rj7             <br>              G:                               .Gr .. E7            <br>              Lu                                 1j   iE            <br>              :G                                  Oi   NX           <br>               B                                  :B  .B            <br>               Fv                               .  O:  G.           <br>               ,O                              ,.. Uv JM            <br>                Gi                           .,... 7S:E   58F       <br>                 B                       ....,...  MBFiivULBN       <br>                 .B                   ..,.,.,..   U5. .             <br>                .7GM.    . ........,.,.,...... ,7Mk      :          <br>              r5j.  Pv. . ........... . . .   ,XBY;vJYjYrBBY        <br>          ,BBBj      EBBE,                .:7k1:         .ku        <br>               .. iUj,  iY1Uj7r::,:,::r7jU5Jr                       <br>               BBBr.        .:;77YvL77;i.                           <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>                                                                    <br>" 
fcontent[3]="                                                                    <br>                                                                    <br>                                                                    <br>                    7uS  . 7P,     ::i                              <br>                  :U,:G1BY7B:XL :Uv::Lq                             <br>                  8Urk: .     ikk .v rY                             <br>                 71:              ri:F                              <br>               :U:                  2E                              <br>              7F;B5   ,.    UBN..    rk                             <br>             rN.:L. .JBi..   ;i:.     F7                            <br>            ,Z     .Y55UU.             O                            <br>            1i                         7U                           <br>            P:                          M                           <br>            iX                          72                          <br>             0:                          G                          <br>             .N                          5i                         <br>              E.                         :N                         <br>              j7                          G                         <br>              i2                          2k.                       <br>               Z                           :L27.                    <br>               N.                             :Juj7Yi,.             <br>               Fi                                Pu LrLX            <br>               i5                                 7U   SF           <br>               .E                                  S7   :0          <br>                Z.                                 .M   ,N          <br>                vY                               .. X;   Z          <br>                .8                             .... vj  YZ          <br>                 F7                          ...... iEiXj           <br>                  O.                      ..,.....  S7,.            <br>                   G               . ....,.,....   uM. ....::       <br>                   ,B:  . ................... .  iNv .:i;iirBB      <br>                  :5:2U,   ....... ... ... .   ,YZ57,       iU      <br>                 2U   .72Er                 :rUui   iYji.           <br>             kBB5:     :P7ruJJ7ri:,:,::rrLYuvi         i7JLr        <br>              ir      kL     .::rr7r7;ri:.                :BS       <br>                    :E,                                    2Y       <br>                 .BB0                                               <br>                                                                    <br>                                                                    <br>                                                                    <br>" 
fcontent[4]="                                                                    <br>                                                                    <br>                                                                    <br>                       i                                            <br>                      uXk. ,1::kr     :JM.                          <br>                     ,N YBrBrLM:qE::Yj: iU                          <br>                     rB7F;..     iLZ, U :F                          <br>                    75i              iJr8                           <br>                  .Xi                  :B                           <br>                 :MiBB   ::    iBB..    .B                          <br>                ,B:,7: ,;BU.:   :ri,.    r8                         <br>                B.     jr iq:             G;                        <br>               7S                         .M                        <br>               Yu                          qr                       <br>                B                          .B                       <br>                J5                          E:                      <br>                 B.                         rX                      <br>                 2Y                          B                      <br>                 :N                          0i                     <br>                  M                          iB7                    <br>                  M.                          .L5Ui   i             <br>                  27                             .L1BULMvu1.        <br>                  rS                                Lk  . iO        <br>                   M                                 ,M    B:       <br>                   M.                                 rG   rB       <br>                   1v                                  B:  E:       <br>                   ,O                               .. YP  YU       <br>                    M,                             ,.. :G :B:       <br>                    iE                          ..,... .BrB,        <br>                     qY                      ..,.,.... UZ:          <br>                      M;              ......,.,...... 7O            <br>                       Z2  . ..........,.,........   2F             <br>                       kqXi    .......... .....   .LFqL.            <br>                      O:  iBB:.               .:7FU01  L1r          <br>                     E7   .Z,iuU1YLri::::i77uU1Jr.  i0.  iBu        <br>                    jU   .B      ,:rr777rri:.        .qL  B8        <br>                 .BBB    M,                            iB:          <br>                 .ri  iBB7                             iBN          <br>                      :q7                                           <br>                                                                    <br>" 
closetag='</font>'
var ie4=document.all&&!document.getElementById
var ns4=document.layers
var DOM2=document.getElementById
var index=0
function changecontent(){
if (index>=fcontent.length)
index=0
if (DOM2){
document.getElementsByClassName("ascii-animation").innerHTML=begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag
}
else if (ie4)
document.all.fscroller.innerHTML=begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag
else if (ns4){
document.fscrollerns.document.fscrollerns_sub.document.write(begintag+fcontent[index].replace(/ /g,"&nbsp;")+closetag)
document.fscrollerns.document.fscrollerns_sub.document.close()
}
index++
setTimeout("changecontent()",delay)
}
if (ie4||DOM2)
//document.write('<div id="fscroller"></div>')
window.onload=changecontent