name = "RPA developer"
type = "data"
link = ""

short_description = "Developer responsible for automating data transfer, querying, and creation processes through pipelines on the client's server (Teleperformance). Additionally, I created a library to optimize developer productivity by simulating the server on the local machine."
languages = ["Python", "Javascript"]
technologies = ["Selenium", "Pandas", "Numpy", "requests", "APIs"]
topics = ["web scraping", "automation", "ETL"]
