JOBS = [
    ["rpa_pidgin", "master"]
]

PROJECTS = [
    ["portfolio", "master"],
    ["mathnets", "main"],
    ["tabacco_net", "main"],
    ["politics_tweets", "master"],
    ["simple_markowitz", "main"],
    ["DataFluids", "master"]
]